% PrologModel
% Generated by Prolog-DMN Converter

eligible_for_loan(Result) :-
    Result = 'approved'.
eligible_for_loan(Result) :-
    Result = 'approved'.
eligible_for_loan(Result) :-
    Result = 'conditional'.
eligible_for_loan(Result) :-
    Result = 'denied'.

calculate_discount(OrderAmount, Discount) :-
    Discount = 20.
calculate_discount(OrderAmount, Discount) :-
    OrderAmount >= 1000,
    Discount = 15.
calculate_discount(OrderAmount, Discount) :-
    OrderAmount < 1000,
    Discount = 10.
calculate_discount(OrderAmount, Discount) :-
    OrderAmount >= 500,
    Discount = 5.
calculate_discount(OrderAmount, Discount) :-
    OrderAmount < 500,
    Discount = 0.