% PrologModel
% Generated by Prolog-DMN Converter

eligible_for_loan(Result) :-
    Result = 'approved'.
eligible_for_loan(Result) :-
    Result = 'approved'.
eligible_for_loan(Result) :-
    Result = 'conditional'.
eligible_for_loan(Result) :-
    Result = 'denied'.