% PrologModel
% Generated by Prolog-DMN Converter

eligible_for_loan(Result) :-
    Result = 'approved'.
eligible_for_loan(Result) :-
    Result = 'approved'.
eligible_for_loan(Result) :-
    Result = 'conditional'.
eligible_for_loan(Result) :-
    Result = 'denied'.

calculate_discount(OrderAmount, Discount) :-
    Discount = 20.
calculate_discount(OrderAmount, Discount) :-
    OrderAmount >= 1000,
    Discount = 15.
calculate_discount(OrderAmount, Discount) :-
    OrderAmount < 1000,
    Discount = 10.
calculate_discount(OrderAmount, Discount) :-
    OrderAmount >= 500,
    Discount = 5.
calculate_discount(OrderAmount, Discount) :-
    OrderAmount < 500,
    Discount = 0.

determine_tax_rate(Income, TaxRate) :-
    Income >= 100000,
    TaxRate = 35.
determine_tax_rate(Income, TaxRate) :-
    Income < 100000,
    TaxRate = 28.
determine_tax_rate(Income, TaxRate) :-
    Income < 50000,
    TaxRate = 22.
determine_tax_rate(Income, TaxRate) :-
    Income < 30000,
    TaxRate = 15.
determine_tax_rate(Income, TaxRate) :-
    Income < 15000,
    TaxRate = 10.